// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBra9cNx_Kej_UneYfnPWVktRT7fWPQw',
    appId: '1:1017496235042:web:6ec976697e71606570ee7b',
    messagingSenderId: '1017496235042',
    projectId: 'thedipaar-news',
    authDomain: 'thedipaar-news.firebaseapp.com',
    storageBucket: 'thedipaar-news.appspot.com',
    measurementId: 'G-HTFCFQBMR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX-wxUqd4VMlJQMRYBnnbGnxWQxIl14Lw',
    appId: '1:1017496235042:android:1bc5aa7878d5e84e70ee7b',
    messagingSenderId: '1017496235042',
    projectId: 'thedipaar-news',
    storageBucket: 'thedipaar-news.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__a_12fBpbbOU7EU_d1hFPRS1H8zUVAw',
    appId: '1:1017496235042:ios:c52065d4f81d215670ee7b',
    messagingSenderId: '1017496235042',
    projectId: 'thedipaar-news',
    storageBucket: 'thedipaar-news.appspot.com',
    iosBundleId: 'com.example.thedipaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB__a_12fBpbbOU7EU_d1hFPRS1H8zUVAw',
    appId: '1:1017496235042:ios:c7b1acc7cc0fa68970ee7b',
    messagingSenderId: '1017496235042',
    projectId: 'thedipaar-news',
    storageBucket: 'thedipaar-news.appspot.com',
    iosBundleId: 'com.example.thedipaar.RunnerTests',
  );
}
